name: Docker Image CI

on:
  push:
    branches: [ main dev ]
  pull_request:
    branches: [ main dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/ocaml-jupyterhub-dockerspawner:${{ steps.extract_branch.outputs.branch }}
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/ocaml-jupyterhub-dockerspawner:${{ steps.extract_branch.outputs.branch }}
